packages:
  - .
  - test/fixtures/*
loglevel: info
onlyBuiltDependencies:
  - "@parcel/watcher"
  - core-js
  - esbuild
  - msgpackr-extract
overrides:
  lodash: ^=4.17.23
preferFrozenLockfile: true
publicHoistPattern:
  - "@commitlint/cli"
  - "@commitlint/cz-commitlint"
  - husky
  - husky
  - lint-staged
  - markdownlint-cli2
  - markdownlint-cli2-formatter-codequality
